### ISSUE TITLE
No unused keys in database

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/multiwallet#16]
On fresh spend from within hindsight, the following panic was produced:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x6daa46]

goroutine 69 [running]:
github.com/OpenBazaar/hindsight/vendor/github.com/btcsuite/btcutil/hdkeychain.(*ExtendedKey).pubKeyBytes(0x0, 0xc42006c800, 0xc420393820, 0x7f5598ce16c8)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/btcsuite/btcutil/hdkeychain/extendedkey.go:150 +0x26
github.com/OpenBazaar/hindsight/vendor/github.com/btcsuite/btcutil/hdkeychain.(*ExtendedKey).Address(0x0, 0xbe3de0, 0x22, 0xc4202c0810, 0xc420393860)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/btcsuite/btcutil/hdkeychain/extendedkey.go:381 +0x2f
github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin.litecoinAddress(0x0, 0xbe3de0, 0x0, 0x9e0360, 0xc4207282e0, 0x7f5598ce16c8)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go:73 +0x50
github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin.(*LitecoinWallet).CurrentAddress(0xc420094500, 0x1, 0x1, 0xc420393ae0)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go:129 +0x55
github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin.(*LitecoinWallet).buildTx.func2(0x8179e0, 0xc42005e400, 0x1, 0x1, 0x1)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin/sign.go:90 +0x37
github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin.newUnsignedTransaction(0xc4202e4020, 0x1, 0x1, 0x222e0, 0xc42005e3c0, 0xc420728280, 0xc4208b2600, 0xc42099ac00, 0xc42099aca0)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin/sign.go:173 +0x3f6
github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin.(*LitecoinWallet).buildTx(0xc420094500, 0x9c40, 0x9e3ca0, 0xc4206f6480, 0x2, 0x0, 0x1, 0x1, 0x1a)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin/sign.go:102 +0x595
github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin.(*LitecoinWallet).Spend(0xc420094500, 0x9c40, 0x9e3ca0, 0xc4206f6480, 0x2, 0x1a, 0x0, 0x0)
        /go/src/github.com/OpenBazaar/hindsight/vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go:215 +0x66
github.com/OpenBazaar/hindsight/tracker.(*TransactionExerciseJob).createAndWatchNewTransaction(0xc4201235c0)
        /go/src/github.com/OpenBazaar/hindsight/tracker/transaction_exercise_job.go:217 +0x33c
github.com/OpenBazaar/hindsight/tracker.(*TransactionExerciseJob).(github.com/OpenBazaar/hindsight/tracker.createAndWatchNewTransaction)-fm()
        /go/src/github.com/OpenBazaar/hindsight/tracker/transaction_exercise_job.go:134 +0x2a
created by time.goFunc
        /usr/local/go/src/time/sleep.go:172 +0x44
```

**Comment by placer14** [comment]
@cpacia found this:
`ws.db.Keys().MarkKeyAsUsed(sa.Addr.ScriptAddress())` should be `ws.km.MarkKeyAsUsed(sa.Addr.ScriptAddress())` on service/wallet_service.go:449

**Comment by placer14** [comment]
Fixed in https://github.com/OpenBazaar/multiwallet/pull/14/commits/6764d7b02c96884e3a6eca027b210bf6e11a075b
