### ISSUE TITLE
panic when sync-ing transactions: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/multiwallet#23]
```
[0m[36m18:44:20.277 [syncTxs] [DEBUG] Downloaded 1 Litecoin transactions
panic: runtime error: slice bounds out of range

goroutine 15338 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/bchutil.DecodeAddress(0x0, 0x0, 0x10e792280, 0x0, 0x0, 0x105704680, 0x10f7ee0d0)
    /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/bchutil/cashaddr.go:385 +0x5f0
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/util.DecodeAddress(0x0, 0x0, 0x10e792280, 0x0, 0x0, 0x0, 0x0)
    /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/util/address.go:17 +0x5c
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).saveSingleTxToDB(0x10e760d00, 0x10f619240, 0x40, 0x1, 0x0, 0x111726000, 0x1, 0x4, 0x111726240, 0x2, ...)
    /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:372 +0x764
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).saveTxsToDB(0x10e760d00, 0x10eb92000, 0x1, 0x1, 0x10fae5350)
    /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:336 +0xd0
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).syncTxs(0x10e760d00, 0x10fae5350)
    /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:321 +0x5b0
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).UpdateState
    /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:210 +0x280
```

I'll update the issue with steps to reproduce shortly.

**Comment by drwasho** [comment]
We're getting this by just running the node, not doing anything special.
